chore: docs and move check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -299,8 +299,9 @@ jobs:
                 2> >(tee build.log >&2) || true
             fi 
 
-            # If build did not fail due to broken pipe, break and continue
-            if ! grep -q "client_loop: send disconnect: Broken pipe" build.log
+            # If build did not fail due to broken pipe, break and continue.
+            # If build.json exits, the build compleated.
+            if ! grep -q "client_loop: send disconnect: Broken pipe" build.log && [ ! -s build.json ]
             then
               echo "No broken pipe, ending attempts"
               break
@@ -308,7 +309,7 @@ jobs:
 
             attempt=$((attempt + 1)) # Increment attempt
 
-            if [ $attempt -lt 10 && ! -s build.json ]
+            if [ $attempt -lt 10 ]
             then
               echo "Broken pipe detected! Will try again in $minutes minutes."
               sleeptime=$((minutes * 60)) # Convert to seconds
