fix: check for build out when checking for broken pipe (#19)
* fix: check for build out when checking for broken pipe

* chore: docs and move check

* chore: spelling

* chore: spelling

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -299,8 +299,9 @@ jobs:
                 2> >(tee build.log >&2) || true
             fi 
 
-            # If build did not fail due to broken pipe, break and continue
-            if ! grep -q "client_loop: send disconnect: Broken pipe" build.log
+            # If build did not fail due to broken pipe, break and continue.
+            # If build.json exists, the build completed.
+            if ! grep -q "client_loop: send disconnect: Broken pipe" build.log && [ ! -s build.json ]
             then
               echo "No broken pipe, ending attempts"
               break
